### ISSUE TITLE
user_photos

### ISSUE THREAD

**Issue by aliakkawi** [darwin-morocho/flutter-facebook-auth#110] opened 2021-06-16 09:29 UTC
Hello and thanks for the useful repo,
I need help with getting user's photos from Facebook. In the login method i included 'user_photos' to the permissions list like the following:

final LoginResult facebookLoginResult =
          await _facebookLogin.login(permissions: [
        'email', 'public_profile',
        'user_photos'
      ]);

By using the 'userId' and 'token' form the AccessToken, i am performing a get request to the Facebook Graph Api
GET /v11.0/{page-id}/photos
Host: graph.facebook.com
 and i am getting an empty data  Status 200 OK:
{
    "data": []
}

After the login i checked the granted permissions for the user on both Android and iOS and they were as the following, 
[openid, public_profile, email]

I

In the past i have been able to get the user's photos using the api, but suddenly it stopped working properly
Please advice me what changes i have to do in order to fix that.
Thanks in advance
![Screen Shot 2021-06-16 at 12 26 44](https://user-images.githubusercontent.com/14969941/122194842-7a7b7d00-ce9e-11eb-81fb-37d5739d101c.png)

**Comment by darwin-morocho** [comment] 2021-06-16 09:55
Hi.  Please use the AccessToken instance and check the grantedPermissions to see if you have the user_photos permissions. The user_photos permissions needs to be approved by Facebook.


Also you can use the getUserData method to get the user images 

FacebookAuth.instance.getUserData(fields:"photos")

**Comment by aliakkawi** [comment] 2021-06-16 09:59
Hello and thanks for your response,
granted permissions are as follow:
[openid, public_profile, email]
My app is still in development  and it is not live yet, i am using pre defined test users.

**Comment by darwin-morocho** [comment] 2021-06-16 10:02
> Hello and thanks for your response,
> granted permissions are as follow:
> [openid, public_profile, email]
> My app is still in development and it is not live yet, i am using pre defined test users.

In that case go to the Facebook user settings  in the Facebook page and delete your app from the list and test the login again

**Comment by aliakkawi** [comment] 2021-06-16 10:11
I've done so but still no photos permission is requested.
![login_fb](https://user-images.githubusercontent.com/14969941/122201063-4e62fa80-cea4-11eb-88aa-28f0e8a2e1c2.png)

**Comment by darwin-morocho** [comment] 2021-06-16 10:20
> I've done so but still no photos permission is requested.
> ![login_fb](https://user-images.githubusercontent.com/14969941/122201063-4e62fa80-cea4-11eb-88aa-28f0e8a2e1c2.png)

Are you testing this with an account that has a role in the app (admin, developer or tester)? Otherwise you of course need to submit the permission for review

**Comment by aliakkawi** [comment] 2021-06-16 10:21
sure, i am using a tester account.

**Comment by darwin-morocho** [comment] 2021-06-16 10:24
> sure, i am using a tester account.

If you try with other permission like user_birthday this is requested?

**Comment by aliakkawi** [comment] 2021-06-16 10:31
yes birthday is requested
![Screenshot_20210616-132925_Facebook](https://user-images.githubusercontent.com/14969941/122203803-15785500-cea7-11eb-8c1c-546ae230185a.jpg)

**Comment by darwin-morocho** [comment] 2021-06-16 14:25
> yes birthday is requested
> ![Screenshot_20210616-132925_Facebook](https://user-images.githubusercontent.com/14969941/122203803-15785500-cea7-11eb-8c1c-546ae230185a.jpg)

Great that means the plugin is working fine. Maybe the problem is in your facebook developer console. Please go to your console and check if you have some alerts.

**Comment by darwin-morocho** [comment] 2021-06-16 14:52
I've tested the user_photos permission and it works fine
```dart
 final result = await _facebookAuth.login(permissions: [
      'email',
      'public_profile',
      'user_photos',
    ]);
```

![Screenshot_1623854127](https://user-images.githubusercontent.com/15864336/122239142-5318b600-ce86-11eb-970c-768fec67d2df.png)

**Comment by aliakkawi** [comment] 2021-06-16 15:55
I am getting this message "Your app has Standard Access to public_profile. To use Facebook Login, switch public_profile to Advanced Access. Get Advanced Access". I've tried to submit a review request before, but in order to be approved i have to send them a walk through video for a working case, so unless i solve the issue i cannot send the request.  By the way i am using flutter_facebook_auth: ^3.3.3-no-nullsafety

**Comment by aliakkawi** [comment] 2021-06-16 15:56
![Screen Shot 2021-06-16 at 18 56 23](https://user-images.githubusercontent.com/14969941/122253145-94d04d80-ced4-11eb-9b58-93be4a353d79.png)

**Comment by darwin-morocho** [comment] 2021-06-16 16:07
Yes the problems is your configuration on the facebook developers console. I cannot help you with that because that depends of facebook. Please contact with facebook support to solve your issue.
https://developers.facebook.com/support/


I'm closing this because is not an issue of this plugin.

**Closed by darwin-morocho** 2021-06-16 16:07 UTC

**Comment by aliakkawi** [comment] 2021-06-16 16:08
Thanks a lot for your help, i really appreciate.
