### ISSUE TITLE
FBSDKCoreKit/FBSDKCoreKit.h file not found

### ISSUE THREAD

**Issue by Wolfaks** [darwin-morocho/flutter-facebook-auth#115] opened 2021-07-01 09:23 UTC
Hello.
I have error in iOS: "FBSDKCoreKit/FBSDKCoreKit.h file not found"

I added the following to the PodFile, after which the error popped up:
`post_install do |installer|
  installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
  end
end`
Otherwise, I had an error: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is
9.0 to 14.0.99.

I use version **3.5.0** of **flutter-facebook-auth.**
Please help me. Thanks.

**Comment by darwin-morocho** [comment] 2021-07-01 12:07
> Hello.
> I have error in iOS: "FBSDKCoreKit/FBSDKCoreKit.h file not found"
> 
> I added the following to the PodFile, after which the error popped up:
> `post_install do |installer| installer.pods_project.targets.each do |target| flutter_additional_ios_build_settings(target) target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0' end end end`
> Otherwise, I had an error: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is
> 9.0 to 14.0.99.
> 
> I use version **3.5.0** of **flutter-facebook-auth.**
> Please help me. Thanks.

hi you don't need to add that code.
In your podfile at the top of this file you need to uncomment the next line 

platform :ios, '9.0'

se tthe value to 9.0

**Comment by Wolfaks** [comment] 2021-07-01 12:14
> In your podfile at the top of this file you need to uncomment the next line
Then i had an error: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

**Comment by Wolfaks** [comment] 2021-07-01 12:15
> hi you don't need to add that code.

Then i had an error: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

platform  is uncomented.

**Comment by darwin-morocho** [comment] 2021-07-01 12:17
in xcode go to the general tab and increase your deployment target

**Comment by darwin-morocho** [comment] 2021-07-01 12:19
![22E3DE1D-0CF1-4300-8A84-56293EEA1B3D](https://user-images.githubusercontent.com/15864336/124123231-ac631680-da3c-11eb-92b3-4d78e783e173.jpeg)

**Comment by Wolfaks** [comment] 2021-07-01 13:28
<img width="1331" alt="Снимок экрана 2021-07-01 в 16 26 02" src="https://user-images.githubusercontent.com/26388092/124132248-49e43780-da89-11eb-9771-ff395b12282e.png">

I did this and it still displays an error (pictured). I made the iOS 10 platform, I can’t below because other libraries do not support version 9.

**Comment by darwin-morocho** [comment] 2021-07-01 13:49
> <img alt="Снимок экрана 2021-07-01 в 16 26 02" width="1331" src="https://user-images.githubusercontent.com/26388092/124132248-49e43780-da89-11eb-9771-ff395b12282e.png">
> 
> I did this and it still displays an error (pictured). I made the iOS 10 platform, I can’t below because other libraries do not support version 9.
> 
> `platform :ios, '10.0'`
> `deployment info: iOS 14.5`

what is the ios version of your simulator?

**Comment by darwin-morocho** [comment] 2021-07-01 13:56
This is not an issue of this plugin so I am closing this

**Closed by darwin-morocho** 2021-07-01 13:56 UTC

**Comment by Wolfaks** [comment] 2021-07-01 14:20
> I think the problem is your simulator please Check running the app in a real device

Other device with 
`platform :ios, '10.0'
  deployment info: iOS 10.0`

<img width="804" alt="Снимок экрана 2021-07-01 в 17 18 19" src="https://user-images.githubusercontent.com/26388092/124139745-941ce700-da90-11eb-87aa-008210603328.png">

**Comment by darwin-morocho** [comment] 2021-07-01 14:22
> > I think the problem is your simulator please Check running the app in a real device
> 
> Other device with
> `platform :ios, '10.0' deployment info: iOS 10.0`
> 
> <img alt="Снимок экрана 2021-07-01 в 17 18 19" width="804" src="https://user-images.githubusercontent.com/26388092/124139745-941ce700-da90-11eb-87aa-008210603328.png">

Are you using swift or objective-c?

**Comment by Wolfaks** [comment] 2021-07-01 14:24
> Are you using swift or objective-c?

Swift

**Comment by darwin-morocho** [comment] 2021-07-01 14:26
Please add all the info requested the issue template

**Comment by Wolfaks** [comment] 2021-07-01 14:36
> myPath__ /ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKCoreKitImport.h:29:10: error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
 #import <FBSDKCoreKit/FBSDKCoreKit.h>
         ^
<unknown>:0: error: could not build Objective-C module 'FBSDKLoginKit'

<img width="863" alt="Снимок экрана 2021-07-01 в 17 34 47" src="https://user-images.githubusercontent.com/26388092/124142426-de9f6300-da92-11eb-97b2-35fa0cc85f52.png">

**Comment by darwin-morocho** [comment] 2021-07-01 14:40
**Describe the bug**
A clear and concise description of what the bug is.

**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by Wolfaks** [comment] 2021-07-01 14:53
<img width="1035" alt="Снимок экрана 2021-07-01 в 17 42 38" src="https://user-images.githubusercontent.com/26388092/124144766-ec55e800-da94-11eb-837e-3a292d80f1e4.png">

**pubspec.yaml**
` The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.1
  flutter_launcher_icons: "^0.9.0"
  http: ^0.13.0
  progress_dialog: ^1.2.4
  connectivity: ^0.4.2
  shared_preferences: ^0.5.6+3
  intl: ^0.16.1
  dio: ^4.0.0
  screen_keep_on: ^0.1.1
  in_app_purchase: ^0.5.2
  google_api_availability: ^3.0.1
  apple_sign_in: ^0.1.0
  flutter_local_notifications: ^5.0.0+1
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_messaging: ^10.0.3
  introduction_screen: ^2.0.0
  appodeal_flutter: ^1.0.0
  flutter_facebook_auth: ^3.5.0
  image_picker: ^0.7.4
  image_picker_platform_interface: ^2.1.0
  keyboard_visibility: ^0.5.6
  flutter_vk_login:
    git:
      url: https://github.com/ObjReponse/flutter_vk_login.git
  flutter_vk_sdk:
    git:
      url: https://github.com/Stmol/flutter_vk_sdk.git
      ref: 0.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icotr.png"
  #image_path_ios: "assets/ico.png"
  #image_path_android: "assets/ico.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/apple.png
    - assets/vk.png
    - assets/instagram.png
    - assets/nophoto.png
    - assets/ico.png
    - assets/ios_vk_login.png
    - assets/insta_login.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Info.plist**

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Social Poster</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb5952826694743422</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>5952826694743422</string>
	<key>FacebookDisplayName</key>
	<string>Social Poster</string>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-2138791796405691~4195024945</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
		<string>fbapi20130214</string>
		<string>fbapi20130410</string>
		<string>fbapi20130702</string>
		<string>fbapi20131010</string>
		<string>fbapi20131219</string>
		<string>fbapi20140410</string>
		<string>fbapi20140116</string>
		<string>fbapi20150313</string>
		<string>fbapi20150629</string>
		<string>fbapi20160328</string>
		<string>fbauth</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>Приложение использует камеру</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Пожалуйста дайте доступ к фотографиям</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Приложение может выбирать изображения</string>
	<key>NSUserTrackingUsageDescription</key>
	<string>Приложение будет отображать персанализированную рекламу.</string>
	<key>SKAdNetworkItems</key>
	<array>
		<dict>
			<key>SKAdNetworkIdentifier</key>
			<string>4pfyvq9l8r.skadnetwork</string>
		</dict>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>`

**AppDelegate.swift**

`import UIKit
import Flutter
import AppTrackingTransparency
import AdSupport
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

        // Use Firebase library to configure APIs
        if FirebaseApp.app() == nil {
            FirebaseApp.configure()
        }

    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    
    if #available(iOS 14, *) {
        ATTrackingManager.requestTrackingAuthorization() { status in
            // Tracking authorization completed. Initialise Appodeal here.
        }
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

}
`
**Android has no problems**

**Comment by darwin-morocho** [comment] 2021-07-01 15:02
You are using `dart >= 2.7` so your project doesn't support `flutter_facebook_auth: ^3.5.0` because this version is for null safety projects you must use `flutter_facebook_auth: ^3.3.3-no-nullsafety` also it seems there is a conflict with you `AppDelegate.swift` because your are initializing the firebase sdk in this file and that is not required on flutter projects.

Also you are using other dependencies that only must be used on dart >= 2.12 (null safety) for example `firebase_core:1.3.0`

**Comment by Wolfaks** [comment] 2021-07-01 18:55
I did a rollback
<img width="586" alt="Снимок экрана 2021-07-01 в 21 55 06" src="https://user-images.githubusercontent.com/26388092/124176026-03a5cd00-dab7-11eb-9375-01af11093fdb.png">

<img width="493" alt="Снимок экрана 2021-07-01 в 21 53 50" src="https://user-images.githubusercontent.com/26388092/124175961-ec66df80-dab6-11eb-9fb1-dea0c55eba33.png">

'FBSDKCoreKit/FBSDKCoreKit.h' file not found #import <FBSDKCoreKit/FBSDKCoreKit.h>
AND
 The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of
    supported deployment target versions is 9.0 to 14.5.99. (in target 'VK-ios-sdk' from project 'Pods')

**Comment by darwin-morocho** [comment] 2021-07-01 19:05
> I did a rollback
> <img alt="Снимок экрана 2021-07-01 в 21 55 06" width="586" src="https://user-images.githubusercontent.com/26388092/124176026-03a5cd00-dab7-11eb-9375-01af11093fdb.png">
> 
> <img alt="Снимок экрана 2021-07-01 в 21 53 50" width="493" src="https://user-images.githubusercontent.com/26388092/124175961-ec66df80-dab6-11eb-9fb1-dea0c55eba33.png">
> 
> 'FBSDKCoreKit/FBSDKCoreKit.h' file not found #import <FBSDKCoreKit/FBSDKCoreKit.h>
> AND
> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of
> supported deployment target versions is 9.0 to 14.5.99. (in target 'VK-ios-sdk' from project 'Pods')

You are wrong not all dependencies has `-no-nullsafety` at the end of the version , you need to go to pub.dev and search depencies compatible before null safety, remember you have multiples dependencies that must be used only on null safety projects.

I recommend go to dart.dev a learn about null safety.

I am locking this because there is not an issue of this plugin

**Comment by darwin-morocho** [comment] 2021-07-03 14:36
Sometimes the error can be fixed using `flutter clean`
