### ISSUE TITLE
iOS native sdk problem

### ISSUE THREAD

**Issue by gianlucainnocente** [darwin-morocho/flutter-facebook-auth#5] opened 2020-04-25 12:38 UTC
Hi,
using the last iOS version on iPhone XS with Facebook native app installed, it doesn't return to the app when the user choose to use Facebook app to login. (see this video: https://filebin.net/2cm23u09ygx52zi3/WhatsApp_Video_2020-04-24_at_14.58.27.mp4?t=o8wy6pge)

Any solutions?

**Comment by darwin-morocho** [comment] 2020-04-25 12:55
> Hi,
> using the last iOS version on iPhone XS with Facebook native app installed, it doesn't return to the app when the user choose to use Facebook app to login. (see this video: https://filebin.net/2cm23u09ygx52zi3/WhatsApp_Video_2020-04-24_at_14.58.27.mp4?t=o8wy6pge)
> 
> Any solutions?

this is a common error when your urls schemes in your info.plist are not configured  correctly. This is not a bug of the library. So I go to close this issue.

Please read https://pub.dev/packages/flutter_facebook_auth#install-on-ios or go to de ios Facebook sdk documentation.

You can check the correct way to configure the iis sdk here https://youtu.be/3vJWV1AOWvQ

**Comment by gianlucainnocente** [comment] 2020-04-27 09:50
Hi, i red the instructions and also watched the video, but my config is correct. (see attached screenshot of my Info.plist in Runner folder).

I think that the problem is when the user choose to use the Facebook native app to login, because if they use webview, it works correctly..

Any ideas?
Thanks

![Schermata 2020-04-27 alle 11 47 11](https://user-images.githubusercontent.com/11719036/80358692-1900e500-887d-11ea-8127-b9e33dbdd55f.png)

**Comment by darwin-morocho** [comment] 2020-04-27 20:20
> Hi, i red the instructions and also watched the video, but my config is correct. (see attached screenshot of my Info.plist in Runner folder).
> 
> I think that the problem is when the user choose to use the Facebook native app to login, because if they use webview, it works correctly..
> 
> Any ideas?
> Thanks
> 
> ![Schermata 2020-04-27 alle 11 47 11](https://user-images.githubusercontent.com/11719036/80358692-1900e500-887d-11ea-8127-b9e33dbdd55f.png)

Yea you are right. I can see the same problem on my iPhone x. I am working to fix this problem and upload a new version soon.

**Comment by darwin-morocho** [comment] 2020-04-27 21:12
> > Hi, i red the instructions and also watched the video, but my config is correct. (see attached screenshot of my Info.plist in Runner folder).
> > I think that the problem is when the user choose to use the Facebook native app to login, because if they use webview, it works correctly..
> > Any ideas?
> > Thanks
> > ![Schermata 2020-04-27 alle 11 47 11](https://user-images.githubusercontent.com/11719036/80358692-1900e500-887d-11ea-8127-b9e33dbdd55f.png)
> 
> Yea you are right. I can see the same problem on my iPhone x. I am working to fix this problem and upload a new version soon.

Thanks for your feedback. In the last version of the facebook ios sdk  you need add some code in your application delegate


first excute `pod install` in your `ios` folder

and in your AppDelegate.swift 
```swift
import UIKit
import Flutter
import FBSDKCoreKit // <--- ADD THIS LINE

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
    ) -> Bool {
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
        GeneratedPluginRegistrant.register(with: self) // <--- ADD THIS LINE
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    
    // <--- OVERRIDE THIS METHOD
    override func application( _ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:] ) -> Bool { ApplicationDelegate.shared.application( app, open: url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation] )
    }
}

```


I will update the readme.md thanks.

Tell me if this fix your problem.

**Closed** 2020-04-28 00:12 UTC
