### ISSUE TITLE
when i installed the facebook app in iphone, facebook login is not worked 

### ISSUE THREAD

**Issue by wangxingxing123654** [darwin-morocho/flutter-facebook-auth#116] opened 2021-07-10 07:30 UTC
when i installed the facebook app in iphone, i click the login button, then a dialog will be show , and i click the log in with the Facebook app, and click the continue, it will return to my app, but it's not login.

**Comment by marslannasr7koncepts** [comment] 2021-07-13 07:07
Did you resolved it.?

> when i installed the facebook app in iphone, i click the login button, then a dialog will be show , and i click the log in with the Facebook app, and click the continue, it will return to my app, but it's not login.

**Comment by darwin-morocho** [comment] 2021-07-16 22:36
@wangxingxing123654  and @marslannasr7koncepts  please follow the issue template to allow me reproduce the error.

Also you can check the example folder and change the example with your credentials and let me know if the problem persists.

**Comment by nguyenlinhnttu** [comment] 2021-07-17 13:22
I'm facing with same problem.
Device android installed facebook app can't login.
So i try to remove facebook app and login by browser it working.

**Comment by darwin-morocho** [comment] 2021-07-17 14:20
> I'm facing with same problem.
> Device android installed facebook app can't login.
> So i try to remove facebook app and login by browser it working.
> Error on facebook app.
> https://imgur.com/Rjz9ifp

This plugin only connect with the native Facebook sdk if you have a wrong configuration in your console I can't do any more. Also go to the oficial Facebook sdk repository and check if other users has the same problem.

**Comment by junaidlodhi22** [comment] 2021-07-31 07:53
having the same problem. 
If the Facebook app is installed. Facebook giving error. if the Facebook app is not installed, and it opens the Facebook login in the browser then it is working.

**Comment by darwin-morocho** [comment] 2021-07-31 12:15
> having the same problem.
> If the Facebook app is installed. Facebook giving error. if the Facebook app is not installed, and it opens the Facebook login in the browser then it is working.

Maybe is a problem with thw facebook sdk for ios the current version in this plugin is 11.0.0  so try to use flutter_facebook_auth:3.4.1  that version use the facebook sdk 9.1.0  first follow the migratiin guide to avoid problems https://facebook.meedu.app/#/migration-guide next install flutter_facebook_auth:3.4.1

**Comment by iamjunaidkhokhar** [comment] 2021-08-02 12:38
it is because you may be adding key hashes with '0x' groups.
try to convert you SHA1 key here http://tomeko.net/online_tools/hex_to_base64.php without checing remove ' "0x" groups from input' 
It worked in my case

**Comment by jlancer** [comment] 2021-08-12 07:38
May be iOS `[AppDelegate application:openURL:options:]` method Blocked
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
    if ([Growing handleUrl:url]) 
        return YES;
    }
    return [super application:app openURL:url options:options];
}
```

**Comment by darwin-morocho** [comment] 2021-08-12 17:41
> May be iOS `[AppDelegate application:openURL:options:]` method blocked
> 
> My AppDelegate.m
> 
> ```
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
>     if ([Growing handleUrl:url]) 
>         return YES;
>     }
>     return [super application:app openURL:url options:options];
> }
> ```
> 
> flutter-facebook-auth/facebook_auth/ios/Classes/SwiftFlutterFacebookAuthPlugin.swift
> 
> ```
> public func application( _ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:] ) -> Bool {
>     let processed = ApplicationDelegate.shared.application(
>         app, open: url,
>         sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String,
>         annotation: options[UIApplication.OpenURLOptionsKey.annotation])
>     return processed;
> }
> ```

I  am not sure because I'm not a objective-c developer for that reason this plugin only works with swift

**Comment by jlancer** [comment] 2021-08-13 04:40
objective-c can also work normally, but it doesn’t work if I write it like this
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
    if ([Growing handleUrl:url]) 
        return YES;
    }
    return NO;
}
```
so if you use other SDKs, they must be compatible, don't return NO directly, but pass backwards

change to `return [super application:app openURL:url options:options];` it works normally

**Comment by darwin-morocho** [comment] 2021-08-20 12:19
I am closing this because we don't have any response from autor

**Closed by darwin-morocho** 2021-08-20 12:19 UTC
Labels: insufficient information
