### ISSUE TITLE
HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID 'MY_APP_ID' does not exist, cannot be loaded due to missing permissions, or does not support this operation.

### ISSUE THREAD

**Issue by jesper372** [darwin-morocho/flutter-facebook-auth#47] opened 2021-02-09 15:02 UTC
When running the app after a clean build, an exception is reported in Android (but not iOS):

> {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID 'MY_APP_ID' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}

The exception only occurs after a clean build, when the app starts; it does not occur when signing in with Facebook (which works). I've followed the instructions in the [plugin documentation](https://pub.dev/packages/flutter_facebook_auth#android) to the letter.

**Comment by darwin-morocho** [comment] 2021-02-09 15:27
@jesper372  duplicated https://github.com/darwin-morocho/flutter-facebook-auth/issues/29

**Comment by jesper372** [comment] 2021-02-09 15:45
Why was this closed? I've followed the suggestions in #29 - they don't resolve my problem.

**Comment by jesper372** [comment] 2021-02-09 15:49
@darwin-morocho I opened this issue specifically because I read through #29 and found that none of the proposed solutions there solve my problem, so just unquestionably marking it as a duplicate of #29 doesn't make sense.

**Comment by darwin-morocho** [comment] 2021-02-09 16:13
> @darwin-morocho I opened this issue specifically because I read through #29 and found that none of the proposed solutions there solve my problem, so just unquestionably marking it as a duplicate of #29 doesn't make sense.

If you are using windows to develop this app is a common error get an invalid hash on Android.

**Comment by darwin-morocho** [comment] 2021-02-09 16:45
> > @darwin-morocho I opened this issue specifically because I read through #29 and found that none of the proposed solutions there solve my problem, so just unquestionably marking it as a duplicate of #29 doesn't make sense.
> 
> If you are using windows to develop this app is a common error get an invalid hash on Android. Also when you run the app in release mode you need add a release hash in your facebook  developer console.
> 
> Also this is not a problem of this plugin is a bad configuration in your facebook developer console, please add an issue in the facebook sdk repository https://github.com/facebook/facebook-android-sdk

**Comment by jesper372** [comment] 2021-02-11 08:25
@darwin-morocho

> If you are using windows to develop this app is a common error get an invalid hash on Android. Also when you run the app in release mode you need add a release hash in your facebook developer console.
Please check your credentials on Android and in your facebook developer console.

I'm seeing this on macOS, not Windows. I'm not yet in release mode. I've checked my credentials.

> Also this is not a problem of this plugin is a bad configuration in your facebook developer console, please add an issue in the facebook sdk repository https://github.com/facebook/facebook-android-sdk

At the same time, this issue has been reopened; should I proceed to add an issue in the Facebook SDK repository, or not?

**Comment by darwin-morocho** [comment] 2021-02-11 13:49
> @darwin-morocho
> 
> > If you are using windows to develop this app is a common error get an invalid hash on Android. Also when you run the app in release mode you need add a release hash in your facebook developer console.
> > Please check your credentials on Android and in your facebook developer console.
> 
> I'm seeing this on macOS, not Windows. I'm not yet in release mode. I've checked my credentials.
> 
> > Also this is not a problem of this plugin is a bad configuration in your facebook developer console, please add an issue in the facebook sdk repository https://github.com/facebook/facebook-android-sdk
> 
> At the same time, this issue has been reopened; should I proceed to add an issue in the Facebook SDK repository, or not?

I've closed this issue because is not a bug of this plugin.

**Closed by darwin-morocho** 2021-02-11 13:49 UTC
